Repository lblod/ember-rdfa-editor-roadsign-regulation-plugin, pull requests merged in 2022-02, with the labels that each got.

#19 Use editor debug component instead of duplicated code (see GN-3152)
  package-lock.json
  package.json
  tests/dummy/app/controllers/application.js
  tests/dummy/app/templates/application.hbs
Labels: enhancement

#20 make classification optional
  addon/components/roadsigns-table.hbs
  addon/models/sign.js
  addon/services/roadsign-registry.js
Labels: bug

#24 Feature/feedback based improvements
  addon/components/editor-plugins/roadsign-regulation-card.js
  addon/components/roadsigns-modal.hbs
  addon/components/roadsigns-modal.js
  addon/services/roadsign-registry.js
  addon/utils/fetchData.js
  package-lock.json
  package.json
Labels: enhancement

#25 Explicit import debug component
  package-lock.json
  tests/dummy/app/components/rdfa-editor-with-debug.js
  tests/dummy/app/templates/application.hbs
Labels: bug

#26 Ember upgrade v3.28
  .eslintrc.js
  package-lock.json
  package.json
  tests/dummy/app/styles/app.scss
Labels: enhancement

#27 Bump editor to 0.50.0
  package-lock.json
  package.json
  tests/dummy/app/styles/app.scss
Labels: internal
